spring:
  port: 8080
  datasource:
    url: jdbc:postgresql://postgres_db:5432/media-content-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

embedding:
  service:
    url:
      audio: http://example.com/audio
      visual: http://example.com/visual
      user_description: http://example.com/user_description
      ml_description: http://example.com/ml_description